@echo off
chcp 65001 > nul
cd /d "%~dp0\..\engine"
title PebbleWorld Fix - Запуск ALT 11
echo ========================================================
echo   PebbleFix (Pebvox) - Запуск обхода в режиме ALT 11
echo   Discord Voice + Web, YouTube 4K, PebbleWorld
echo ========================================================
start "zapret: ALT11" /min "%~dp0\..\engine\bin\winws.exe" --wf-tcp=80,443,2053,2083,2087,2096,8443,1024-65535 --wf-udp=443,19294-19344,50000-50100,1024-65535 ^
--filter-udp=443 --hostlist="%~dp0\..\engine\lists\list-general.txt" --hostlist="%~dp0\..\engine\lists\list-general-user.txt" --hostlist-exclude="%~dp0\..\engine\lists\list-exclude.txt" --hostlist-exclude="%~dp0\..\engine\lists\list-exclude-user.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude-user.txt" --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic="%~dp0\..\engine\bin\quic_initial_www_google_com.bin" --new ^
--filter-udp=19294-19344,50000-50100 --filter-l7=discord,stun --dpi-desync=fake --dpi-desync-fake-discord="%~dp0\..\engine\bin\ACTIVE_DISCORD_UDP.bin" --dpi-desync-fake-stun="%~dp0\..\engine\bin\ACTIVE_DISCORD_UDP.bin" --dpi-desync-repeats=6 --new ^
--filter-tcp=2053,2083,2087,2096,8443 --hostlist-domains=discord.media --dpi-desync=fake,multisplit --dpi-desync-split-seqovl=681 --dpi-desync-split-pos=1 --dpi-desync-fooling=ts --dpi-desync-repeats=8 --dpi-desync-split-seqovl-pattern="%~dp0\..\engine\bin\tls_clienthello_www_google_com.bin" --dpi-desync-fake-tls="%~dp0\..\engine\bin\tls_clienthello_www_google_com.bin" --new ^
--filter-tcp=443 --hostlist="%~dp0\..\engine\lists\list-google.txt" --ip-id=zero --dpi-desync=fake,multisplit --dpi-desync-split-seqovl=681 --dpi-desync-split-pos=1 --dpi-desync-fooling=ts --dpi-desync-repeats=8 --dpi-desync-split-seqovl-pattern="%~dp0\..\engine\bin\tls_clienthello_www_google_com.bin" --dpi-desync-fake-tls="%~dp0\..\engine\bin\tls_clienthello_www_google_com.bin" --new ^
--filter-tcp=80,443 --hostlist="%~dp0\..\engine\lists\list-general.txt" --hostlist="%~dp0\..\engine\lists\list-general-user.txt" --hostlist-exclude="%~dp0\..\engine\lists\list-exclude.txt" --hostlist-exclude="%~dp0\..\engine\lists\list-exclude-user.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude-user.txt" --dpi-desync=fake,multisplit --dpi-desync-split-seqovl=664 --dpi-desync-split-pos=1 --dpi-desync-fooling=ts --dpi-desync-repeats=8 --dpi-desync-split-seqovl-pattern="%~dp0\..\engine\bin\tls_clienthello_max_ru.bin" --dpi-desync-fake-tls="%~dp0\..\engine\bin\stun2.bin" --dpi-desync-fake-tls="%~dp0\..\engine\bin\tls_clienthello_max_ru.bin" --dpi-desync-fake-http="%~dp0\..\engine\bin\tls_clienthello_max_ru.bin" --new ^
--filter-udp=443 --ipset="%~dp0\..\engine\lists\ipset-all.txt" --hostlist-exclude="%~dp0\..\engine\lists\list-exclude.txt" --hostlist-exclude="%~dp0\..\engine\lists\list-exclude-user.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude-user.txt" --dpi-desync=fake --dpi-desync-repeats=11 --dpi-desync-fake-quic="%~dp0\..\engine\bin\quic_initial_www_google_com.bin" --new ^
--filter-tcp=80,443,8443 --ipset="%~dp0\..\engine\lists\ipset-all.txt" --hostlist-exclude="%~dp0\..\engine\lists\list-exclude.txt" --hostlist-exclude="%~dp0\..\engine\lists\list-exclude-user.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude-user.txt" --dpi-desync=fake,multisplit --dpi-desync-split-seqovl=664 --dpi-desync-split-pos=1 --dpi-desync-fooling=ts --dpi-desync-repeats=8 --dpi-desync-split-seqovl-pattern="%~dp0\..\engine\bin\tls_clienthello_max_ru.bin" --dpi-desync-fake-tls="%~dp0\..\engine\bin\stun2.bin" --dpi-desync-fake-tls="%~dp0\..\engine\bin\tls_clienthello_max_ru.bin" --dpi-desync-fake-http="%~dp0\..\engine\bin\tls_clienthello_max_ru.bin" --new ^
--filter-tcp=1024-65535 --ipset="%~dp0\..\engine\lists\ipset-all.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude-user.txt" --dpi-desync=fake,multisplit --dpi-desync-any-protocol=1 --dpi-desync-cutoff=n4 --dpi-desync-split-seqovl=664 --dpi-desync-split-pos=1 --dpi-desync-fooling=ts --dpi-desync-repeats=8 --dpi-desync-split-seqovl-pattern="%~dp0\..\engine\bin\tls_clienthello_max_ru.bin" --dpi-desync-fake-tls="%~dp0\..\engine\bin\stun2.bin" --dpi-desync-fake-tls="%~dp0\..\engine\bin\tls_clienthello_max_ru.bin" --dpi-desync-fake-http="%~dp0\..\engine\bin\tls_clienthello_max_ru.bin" --dpi-desync-fake-unknown="%~dp0\..\engine\bin\stun2.bin" --dpi-desync-fake-unknown="%~dp0\..\engine\bin\tls_clienthello_max_ru.bin" --new ^
--filter-udp=1024-65535 --ipset="%~dp0\..\engine\lists\ipset-all.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude.txt" --ipset-exclude="%~dp0\..\engine\lists\ipset-exclude-user.txt" --dpi-desync=fake --dpi-desync-repeats=10 --dpi-desync-any-protocol=1 --dpi-desync-fake-unknown-udp="%~dp0\..\engine\bin\ACTIVE_GAME_UDP.bin" --dpi-desync-cutoff=n4
echo Обход успешно запущен! Окно свернуто в трей.
